import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ExternalLink, ScrollText, Star, } from "lucide-react";
import { EmptyState } from "../components/empty-state.js";
import { LoadingIndicator } from "../components/loading-indicator.js";
import { useProjects } from "../lib/projects.js";
export default function ProjectsPage() {
    const { projects, loading, error } = useProjects();
    return (_jsxs("div", { className: "page reveal", children: [_jsxs("header", { className: "page-head", children: [_jsx("p", { className: "eyebrow", children: "projects" }), _jsx("h1", { children: "some of my projects, scripts" })] }), loading ? (_jsx(LoadingIndicator, {})) : error ? (_jsx(EmptyState, { title: "github did not load", description: error })) : projects.length ? (_jsx("div", { className: "project-grid project-image-grid", children: projects.map((project) => (_jsxs("article", { className: "project-card project-image-card", children: [project.thumbnail ? (_jsx("img", { className: "project-card-background", src: project.thumbnail, alt: "", loading: "lazy" })) : null, _jsx("div", { className: "project-card-shade", "aria-hidden": "true" }), _jsxs("div", { className: "project-card-content", children: [_jsxs("div", { className: "project-card-top", children: [_jsx("strong", { className: "project-card-name", children: project.name }), _jsxs("div", { className: "project-card-meta", children: [typeof project.stars === "number" ? (_jsxs("span", { children: [_jsx(Star, {}), project.stars] })) : null, project.language ? (_jsx("span", { children: project.language })) : null, project.license ? (_jsxs("span", { children: [_jsx(ScrollText, {}), project.license] })) : null] })] }), _jsxs("div", { className: "project-card-bottom", children: [_jsx("p", { children: project.description }), project.tags.length ? (_jsx("div", { className: "project-card-tags", children: project.tags.map((tag) => (_jsx("span", { children: tag }, tag))) })) : null, _jsxs("a", { className: "project-open-button", href: project.href, target: "_blank", rel: "noreferrer", children: [_jsx("span", { children: "open repository" }), _jsx(ExternalLink, {})] })] })] })] }, project.repo))) })) : (_jsx(EmptyState, { title: "no projects", description: "i forgot to add the stuff sorry" }))] }));
}
